### ISSUE TITLE
Docker container can't connect to DB

### ISSUE THREAD

**Issue by mini-turtle** [GatorEducator/quizagator#45]
Followed all the instructions on docker hub -- got this error after trying to register a new user:

[2019-05-27 10:57:24,926] ERROR in app: Exception on /login/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/quizagator/application/login.py", line 26, in login
    [form_data["username"]],
  File "/quizagator/application/db_connect.py", line 140, in query_db
    cur = get_db().execute(query, args)
  File "/quizagator/application/db_connect.py", line 122, in get_db
    context_globals.db = db_init()
  File "/quizagator/application/db_connect.py", line 15, in db_init
    conn = sqlite3.connect(database_path)
sqlite3.OperationalError: unable to open database file
ERROR: unable to open database file

**Comment by Cronus89** [comment]
I've got the same error, I cant seem to find any documentation on this webapp?
